### PR TITLE
Add ca certificates to dockerimage

### PR DESCRIPTION
**Pull request by blacs30**
Currently I get errors while lcm is running:

```
time="2020-06-12T12:02:40Z" level=warning msg="Error fetching latest version: err: Get \"https://api.github.com/repos/hashicorp/terraform/releases/latest\": x509: certificate signed by unknown authority" repo=hashicorp/terraform
```

The reason for that is that the dockerimage doesn't contain the public ca certs and therefore can't trust the ssl connection.

### CODE REVIEW

**Comment by arminc** [comment]
My bad. I think it would be better to copy the certs from alpine and keep the binary in the scratch container from the security perspective.

**Comment by blacs30** [comment]
Good point. I’ll update the PR.

**Comment by blacs30** [comment]
When could we see the next release including this? Especially an updated docker image would be great.

**Comment by arminc** [comment]
I wanted to add some other things in but then got stuck because not time. I will do a release tomorrow

**Pull request merged**
